// LayerShellWindow wraps the Wayland layer-shell protocol.
// On X11 / XWayland this falls back to a frameless always-on-top window
// at the requested edge using setWindowFlags and QScreen geometry.
// The fallback is detected at runtime: if wl_display is null we are on X11.

#include "LayerShellWindow.h"

#include <QGuiApplication>
#include <QScreen>
#include <qpa/qplatformnativeinterface.h>

// Generated by qtwaylandscanner from wlr-layer-shell-unstable-v1.xml
#include "wayland-wlr-layer-shell-unstable-v1-client-protocol.h"

#include <wayland-client.h>

// ── Wayland registry callbacks (plain C functions with self pointer in data) ──

static void registryGlobal(void *data, wl_registry *registry,
                            uint32_t name, const char *interface, uint32_t version)
{
    auto *self = static_cast<LayerShellWindow *>(data);
    if (strcmp(interface, zwlr_layer_shell_v1_interface.name) == 0) {
        self->m_layerShell = static_cast<zwlr_layer_shell_v1 *>(
            wl_registry_bind(registry, name, &zwlr_layer_shell_v1_interface,
                             qMin(version, 4u)));
    }
}

static void registryGlobalRemove(void *, wl_registry *, uint32_t) {}

static const wl_registry_listener s_registryListener = {
    registryGlobal,
    registryGlobalRemove,
};

// ── Layer-surface event callbacks ──────────────────────────────────────────

static void layerSurfaceConfigure(void *data, zwlr_layer_surface_v1 *surface,
                                  uint32_t serial, uint32_t width, uint32_t height)
{
    zwlr_layer_surface_v1_ack_configure(surface, serial);
    auto *self = static_cast<LayerShellWindow *>(data);
    if (width > 0 && height > 0)
        self->resize(static_cast<int>(width), static_cast<int>(height));
}

static void layerSurfaceClosed(void *data, zwlr_layer_surface_v1 *)
{
    auto *self = static_cast<LayerShellWindow *>(data);
    self->close();
}

static const zwlr_layer_surface_v1_listener s_layerSurfaceListener = {
    layerSurfaceConfigure,
    layerSurfaceClosed,
};

// ── LayerShellWindow ───────────────────────────────────────────────────────

LayerShellWindow::LayerShellWindow(QWindow *parent)
    : QQuickWindow(parent)
{
    // Detect Wayland by checking for the native interface
    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (ni) {
        wl_display *display = static_cast<wl_display *>(
            ni->nativeResourceForIntegration("wl_display"));
        m_isWayland = (display != nullptr);

        if (m_isWayland) {
            // Obtain the layer-shell global from the Wayland registry
            wl_registry *registry = wl_display_get_registry(display);
            wl_registry_add_listener(registry, &s_registryListener, this);
            wl_display_roundtrip(display);
        }
    }

    setFlags(Qt::FramelessWindowHint | Qt::WindowDoesNotAcceptFocus);
    setColor(Qt::transparent);
}

LayerShellWindow::~LayerShellWindow()
{
    if (m_layerSurface)
        zwlr_layer_surface_v1_destroy(m_layerSurface);
    if (m_layerShell)
        zwlr_layer_shell_v1_destroy(m_layerShell);
}

void LayerShellWindow::exposeEvent(QExposeEvent *event)
{
    QQuickWindow::exposeEvent(event);
    if (!m_layerShellApplied && isExposed())
        applyLayerShell();
}

void LayerShellWindow::applyLayerShell()
{
    m_layerShellApplied = true;
    if (m_isWayland && m_layerShell)
        setupWaylandLayerSurface();
    else
        applyX11Fallback();
}

void LayerShellWindow::setupWaylandLayerSurface()
{
    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (!ni) return;

    wl_surface *surface = static_cast<wl_surface *>(
        ni->nativeResourceForWindow("wl_surface", this));
    if (!surface) return;

    wl_output *output = nullptr;
    if (screen()) {
        output = static_cast<wl_output *>(
            ni->nativeResourceForScreen("wl_output", screen()));
    }

    m_layerSurface = zwlr_layer_shell_v1_get_layer_surface(
        m_layerShell, surface, output,
        ZWLR_LAYER_SHELL_V1_LAYER_TOP,
        "kdock");

    if (!m_layerSurface) return;

    // Anchor bitmask from dock position string
    uint32_t anchorBits = 0;
    if (m_anchor == QStringLiteral("bottom")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
    } else if (m_anchor == QStringLiteral("top")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
    } else if (m_anchor == QStringLiteral("left")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
    } else {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
    }
    zwlr_layer_surface_v1_set_anchor(m_layerSurface, anchorBits);

    // Exclusive zone = dock thickness so maximised windows stop at the dock edge
    zwlr_layer_surface_v1_set_exclusive_zone(m_layerSurface, m_thickness);

    const bool horizontal = (m_anchor == QStringLiteral("bottom") || m_anchor == QStringLiteral("top"));
    const uint32_t w = horizontal ? 0 : static_cast<uint32_t>(m_thickness);
    const uint32_t h = horizontal ? static_cast<uint32_t>(m_thickness) : 0;
    zwlr_layer_surface_v1_set_size(m_layerSurface, w, h);

    zwlr_layer_surface_v1_add_listener(m_layerSurface, &s_layerSurfaceListener, this);

    wl_surface_commit(surface);
}

void LayerShellWindow::applyX11Fallback()
{
    QScreen *scr = screen() ? screen() : QGuiApplication::primaryScreen();
    if (!scr) return;

    const QRect screenGeom = scr->availableGeometry();
    int x = 0, y = 0, w = 0, h = 0;

    if (m_anchor == QStringLiteral("bottom")) {
        w = screenGeom.width();
        h = m_thickness;
        x = screenGeom.x();
        y = screenGeom.y() + screenGeom.height() - h;
    } else if (m_anchor == QStringLiteral("top")) {
        w = screenGeom.width();
        h = m_thickness;
        x = screenGeom.x();
        y = screenGeom.y();
    } else if (m_anchor == QStringLiteral("left")) {
        w = m_thickness;
        h = screenGeom.height();
        x = screenGeom.x();
        y = screenGeom.y();
    } else {
        w = m_thickness;
        h = screenGeom.height();
        x = screenGeom.x() + screenGeom.width() - w;
        y = screenGeom.y();
    }

    setFlags(Qt::FramelessWindowHint | Qt::WindowStaysOnTopHint | Qt::WindowDoesNotAcceptFocus);
    setGeometry(x, y, w, h);
}

// ── Properties ────────────────────────────────────────────────────────────

QString LayerShellWindow::anchor() const { return m_anchor; }
void LayerShellWindow::setAnchor(const QString &a) {
    if (m_anchor != a) { m_anchor = a; emit anchorChanged(); }
}

int LayerShellWindow::thickness() const { return m_thickness; }
void LayerShellWindow::setThickness(int px) {
    if (m_thickness != px) { m_thickness = px; emit geometrySettingsChanged(); }
}

int LayerShellWindow::length() const { return m_length; }
void LayerShellWindow::setLength(int px) {
    if (m_length != px) { m_length = px; emit geometrySettingsChanged(); }
}
