// LayerShellWindow wraps the Wayland layer-shell protocol.
// On X11 / XWayland this falls back to a frameless always-on-top window
// at the requested edge using setWindowFlags and QScreen geometry.

#include "LayerShellWindow.h"

#include <QGuiApplication>
#include <QScreen>
#include <QShowEvent>
#include <qpa/qplatformnativeinterface.h>

#ifdef HAVE_KF6_WINDOWSYSTEM
#include <KWindowEffects>
#endif

// Generated by qtwaylandscanner from wlr-layer-shell-unstable-v1.xml
#include "wayland-wlr-layer-shell-unstable-v1-client-protocol.h"

#include <wayland-client.h>

// ── Wayland registry callbacks ─────────────────────────────────────────────

static void registryGlobal(void *data, wl_registry *registry,
                            uint32_t name, const char *interface, uint32_t version)
{
    auto *self = static_cast<LayerShellWindow *>(data);
    if (strcmp(interface, zwlr_layer_shell_v1_interface.name) == 0) {
        self->m_layerShell = static_cast<zwlr_layer_shell_v1 *>(
            wl_registry_bind(registry, name, &zwlr_layer_shell_v1_interface,
                             qMin(version, 4u)));
    }
}

static void registryGlobalRemove(void *, wl_registry *, uint32_t) {}

static const wl_registry_listener s_registryListener = {
    registryGlobal,
    registryGlobalRemove,
};

// ── Layer-surface event callbacks ──────────────────────────────────────────

static void layerSurfaceConfigure(void *data, zwlr_layer_surface_v1 *surface,
                                  uint32_t serial, uint32_t width, uint32_t height)
{
    zwlr_layer_surface_v1_ack_configure(surface, serial);
    auto *self = static_cast<LayerShellWindow *>(data);
    if (width > 0 && height > 0) {
        const int w = static_cast<int>(width);
        const int h = static_cast<int>(height);
        QMetaObject::invokeMethod(self, [self, w, h]() {
            self->resize(w, h);
        }, Qt::QueuedConnection);
    }
}

static void layerSurfaceClosed(void *data, zwlr_layer_surface_v1 *)
{
    auto *self = static_cast<LayerShellWindow *>(data);
    QMetaObject::invokeMethod(self, &LayerShellWindow::close, Qt::QueuedConnection);
}

static const zwlr_layer_surface_v1_listener s_layerSurfaceListener = {
    layerSurfaceConfigure,
    layerSurfaceClosed,
};

// ── LayerShellWindow ───────────────────────────────────────────────────────

LayerShellWindow::LayerShellWindow()
    : QQuickView()
{
    // BypassWindowManagerHint prevents Qt's Wayland QPA from assigning
    // xdg-shell to this surface, leaving a bare wl_surface we can assign
    // the layer-shell role ourselves.
    // NOTE: Do NOT add Qt::WindowDoesNotAcceptFocus here. On Qt's Wayland QPA
    // that flag causes the wl_surface input region to be set to empty, which
    // blocks ALL pointer events — not just keyboard focus. Keyboard exclusivity
    // is handled via zwlr_layer_surface_v1_set_keyboard_interactivity(NONE).
    setFlags(Qt::BypassWindowManagerHint | Qt::FramelessWindowHint);
    setColor(Qt::transparent);
    setResizeMode(QQuickView::SizeRootObjectToView);

    detectWayland();
}

LayerShellWindow::~LayerShellWindow()
{
    if (m_layerSurface)
        zwlr_layer_surface_v1_destroy(m_layerSurface);
    if (m_layerShell)
        zwlr_layer_shell_v1_destroy(m_layerShell);
}

void LayerShellWindow::detectWayland()
{
    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (!ni) return;

    auto *display = static_cast<wl_display *>(
        ni->nativeResourceForIntegration("wl_display"));
    if (!display) return;

    m_isWayland = true;

    wl_registry *registry = wl_display_get_registry(display);
    wl_registry_add_listener(registry, &s_registryListener, this);
    wl_display_roundtrip(display);
}

void LayerShellWindow::showEvent(QShowEvent *event)
{
    QQuickView::showEvent(event);

    if (m_shellApplied) return;
    m_shellApplied = true;

    if (m_isWayland && m_layerShell)
        setupWaylandLayerSurface();
    else
        applyX11Geometry();

#ifdef HAVE_KF6_WINDOWSYSTEM
    KWindowEffects::enableBlurBehind(this, m_blurEnabled);
#endif
}

void LayerShellWindow::setBlurEnabled(bool enabled)
{
    m_blurEnabled = enabled;
#ifdef HAVE_KF6_WINDOWSYSTEM
    if (isVisible())
        KWindowEffects::enableBlurBehind(this, m_blurEnabled);
#endif
}

void LayerShellWindow::setupWaylandLayerSurface()
{
    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (!ni) return;

    auto *surface = static_cast<wl_surface *>(
        ni->nativeResourceForWindow("wl_surface", this));
    if (!surface) return;

    wl_output *output = nullptr;
    if (screen()) {
        output = static_cast<wl_output *>(
            ni->nativeResourceForScreen("wl_output", screen()));
    }

    m_layerSurface = zwlr_layer_shell_v1_get_layer_surface(
        m_layerShell, surface, output,
        ZWLR_LAYER_SHELL_V1_LAYER_TOP,
        "kdock");
    if (!m_layerSurface) return;

    uint32_t anchorBits = 0;
    if (m_anchor == QStringLiteral("bottom")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
    } else if (m_anchor == QStringLiteral("top")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
    } else if (m_anchor == QStringLiteral("left")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
    } else {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
    }
    zwlr_layer_surface_v1_set_anchor(m_layerSurface, anchorBits);

    // Exclusive zone reserves screen space so maximised windows don't overlap.
    // Uses m_exclusiveZone (visual strip height) not m_thickness (full window height).
    zwlr_layer_surface_v1_set_exclusive_zone(m_layerSurface, m_exclusiveZone);

    const bool horizontal = (m_anchor == QStringLiteral("bottom")
                          || m_anchor == QStringLiteral("top"));
    const uint32_t w = horizontal ? 0 : static_cast<uint32_t>(m_thickness);
    const uint32_t h = horizontal ? static_cast<uint32_t>(m_thickness) : 0;
    zwlr_layer_surface_v1_set_size(m_layerSurface, w, h);

    // Prevent the dock from stealing keyboard focus. Pointer events are
    // unaffected — they're controlled by the wl_surface input region, not this.
    zwlr_layer_surface_v1_set_keyboard_interactivity(
        m_layerSurface,
        ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_NONE);

    zwlr_layer_surface_v1_add_listener(m_layerSurface, &s_layerSurfaceListener, this);

    // Passing NULL to set_input_region resets to "whole surface accepts input".
    // This undoes any empty region that Qt may have set due to window flags,
    // ensuring pointer events are delivered even without keyboard focus.
    wl_surface_set_input_region(surface, nullptr);

    wl_surface_commit(surface);

    // Wait for the compositor to send us the first configure event so we
    // know our actual geometry before the first frame is rendered.
    auto *display = static_cast<wl_display *>(
        ni->nativeResourceForIntegration("wl_display"));
    if (display)
        wl_display_roundtrip(display);
}

void LayerShellWindow::applyX11Geometry()
{
    QScreen *scr = screen() ? screen() : QGuiApplication::primaryScreen();
    if (!scr) return;

    setFlags(Qt::BypassWindowManagerHint | Qt::FramelessWindowHint
             | Qt::WindowStaysOnTopHint);

    const QRect geom = scr->availableGeometry();

    if (m_anchor == QStringLiteral("bottom")) {
        setGeometry(geom.x(), geom.y() + geom.height() - m_thickness,
                    geom.width(), m_thickness);
    } else if (m_anchor == QStringLiteral("top")) {
        setGeometry(geom.x(), geom.y(), geom.width(), m_thickness);
    } else if (m_anchor == QStringLiteral("left")) {
        setGeometry(geom.x(), geom.y(), m_thickness, geom.height());
    } else {
        setGeometry(geom.x() + geom.width() - m_thickness, geom.y(),
                    m_thickness, geom.height());
    }
}

void LayerShellWindow::setAnchor(const QString &anchor)
{
    m_anchor = anchor;
}

void LayerShellWindow::setThickness(int px)
{
    m_thickness = px;
}

void LayerShellWindow::setExclusiveZone(int px)
{
    m_exclusiveZone = px;
}

void LayerShellWindow::applyGeometryUpdate()
{
    if (!m_isWayland || !m_layerSurface) return;

    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (!ni) return;

    auto *surface = static_cast<wl_surface *>(
        ni->nativeResourceForWindow("wl_surface", this));
    if (!surface) return;

    zwlr_layer_surface_v1_set_exclusive_zone(m_layerSurface, m_exclusiveZone);

    const bool horizontal = (m_anchor == QStringLiteral("bottom")
                          || m_anchor == QStringLiteral("top"));
    const uint32_t w = horizontal ? 0 : static_cast<uint32_t>(m_thickness);
    const uint32_t h = horizontal ? static_cast<uint32_t>(m_thickness) : 0;
    zwlr_layer_surface_v1_set_size(m_layerSurface, w, h);

    wl_surface_commit(surface);

    auto *display = static_cast<wl_display *>(
        ni->nativeResourceForIntegration("wl_display"));
    if (display)
        wl_display_roundtrip(display);
}
