// LayerShellWindow wraps the Wayland layer-shell protocol.
// On X11 / XWayland this falls back to a frameless always-on-top window
// at the requested edge using setWindowFlags and QScreen geometry.

#include "LayerShellWindow.h"
#include "LayerShellGlobal.h"

#include <QGuiApplication>
#include <QRegion>
#include <QResizeEvent>
#include <QScreen>
#include <QShowEvent>
#include <qpa/qplatformnativeinterface.h>

#ifdef HAVE_KF6_WINDOWSYSTEM
#include <KWindowEffects>
#endif

// Generated by qtwaylandscanner from wlr-layer-shell-unstable-v1.xml
#include "wayland-wlr-layer-shell-unstable-v1-client-protocol.h"

#include <wayland-client.h>

// Input-region thickness while auto-hidden: thin enough to stay out of the
// way, thick enough for the compositor to still deliver the hover that
// reveals the dock. The surface itself keeps its full size — only this band
// along the anchored edge accepts pointer events while hidden.
static constexpr int kRevealStripPx = 2;

// ── Layer-surface event callbacks ──────────────────────────────────────────

static void layerSurfaceConfigure(void *data, zwlr_layer_surface_v1 *surface,
                                  uint32_t serial, uint32_t width, uint32_t height)
{
    zwlr_layer_surface_v1_ack_configure(surface, serial);
    auto *self = static_cast<LayerShellWindow *>(data);
    if (width > 0 && height > 0) {
        const int w = static_cast<int>(width);
        const int h = static_cast<int>(height);
        QMetaObject::invokeMethod(self, [self, w, h]() {
            self->resize(w, h);
        }, Qt::QueuedConnection);
    }
}

static void layerSurfaceClosed(void *data, zwlr_layer_surface_v1 *)
{
    auto *self = static_cast<LayerShellWindow *>(data);
    QMetaObject::invokeMethod(self, &LayerShellWindow::close, Qt::QueuedConnection);
}

static const zwlr_layer_surface_v1_listener s_layerSurfaceListener = {
    layerSurfaceConfigure,
    layerSurfaceClosed,
};

static zwlr_layer_shell_v1_layer layerEnum(const QString &name)
{
    if (name == QStringLiteral("background")) return ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND;
    if (name == QStringLiteral("bottom"))     return ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM;
    if (name == QStringLiteral("overlay"))    return ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY;
    return ZWLR_LAYER_SHELL_V1_LAYER_TOP;
}

// ── LayerShellWindow ───────────────────────────────────────────────────────

LayerShellWindow::LayerShellWindow()
    : QQuickView()
{
    // BypassWindowManagerHint prevents Qt's Wayland QPA from assigning
    // xdg-shell to this surface, leaving a bare wl_surface we can assign
    // the layer-shell role ourselves.
    // NOTE: Do NOT add Qt::WindowDoesNotAcceptFocus here. On Qt's Wayland QPA
    // that flag causes the wl_surface input region to be set to empty, which
    // blocks ALL pointer events — not just keyboard focus. Keyboard exclusivity
    // is handled via zwlr_layer_surface_v1_set_keyboard_interactivity(NONE).
    setFlags(Qt::BypassWindowManagerHint | Qt::FramelessWindowHint);
    setColor(Qt::transparent);
    setResizeMode(QQuickView::SizeRootObjectToView);

    detectWayland();
}

LayerShellWindow::~LayerShellWindow()
{
    if (m_layerSurface)
        zwlr_layer_surface_v1_destroy(m_layerSurface);
    // m_layerShell is owned by LayerShellGlobal and shared with popups.
}

void LayerShellWindow::detectWayland()
{
    // LayerShellGlobal owns the registry round-trip; the dock and its popups
    // share the one bound zwlr_layer_shell_v1.
    m_isWayland  = LayerShellGlobal::isWayland();
    m_layerShell = LayerShellGlobal::shell();
}

void LayerShellWindow::showEvent(QShowEvent *event)
{
    QQuickView::showEvent(event);

    if (m_shellApplied) return;
    m_shellApplied = true;

    if (m_isWayland && m_layerShell)
        setupWaylandLayerSurface();
    else
        applyX11Geometry();

    // The surface only exists from here on, so this is the earliest point a
    // hidden-at-startup dock can have its reveal-strip input region applied.
    applyInputMask();

#ifdef HAVE_KF6_WINDOWSYSTEM
    KWindowEffects::enableBlurBehind(this, m_blurEnabled);
#endif
}

void LayerShellWindow::setBlurEnabled(bool enabled)
{
    m_blurEnabled = enabled;
#ifdef HAVE_KF6_WINDOWSYSTEM
    if (isVisible())
        KWindowEffects::enableBlurBehind(this, m_blurEnabled);
#endif
}

void LayerShellWindow::setupWaylandLayerSurface()
{
    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (!ni) return;

    auto *surface = static_cast<wl_surface *>(
        ni->nativeResourceForWindow("wl_surface", this));
    if (!surface) return;

    wl_output *output = nullptr;
    if (screen()) {
        output = static_cast<wl_output *>(
            ni->nativeResourceForScreen("wl_output", screen()));
    }

    // The dock defaults to the TOP layer, in front of ordinary windows — a
    // dock behind them can't be seen over a maximised window, which makes
    // both auto-hide and dodge pointless. This used to be LAYER_BOTTOM purely
    // so the context menu could appear above the dock; menus now get their own
    // OVERLAY surface (LayerShellPopup) and no longer need that workaround.
    m_layerSurface = zwlr_layer_shell_v1_get_layer_surface(
        m_layerShell, surface, output,
        layerEnum(m_layer),
        "kdock");
    if (!m_layerSurface) return;

    uint32_t anchorBits = 0;
    if (m_anchor == QStringLiteral("bottom")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
    } else if (m_anchor == QStringLiteral("top")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT;
    } else if (m_anchor == QStringLiteral("left")) {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
    } else {
        anchorBits = ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP
                   | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM;
    }
    zwlr_layer_surface_v1_set_anchor(m_layerSurface, anchorBits);

    // Exclusive zone reserves screen space so maximised windows don't overlap.
    // Uses m_exclusiveZone (visual strip height) not m_thickness (full window height).
    zwlr_layer_surface_v1_set_exclusive_zone(m_layerSurface, m_exclusiveZone);

    const bool horizontal = (m_anchor == QStringLiteral("bottom")
                          || m_anchor == QStringLiteral("top"));
    const uint32_t w = horizontal ? 0 : static_cast<uint32_t>(m_thickness);
    const uint32_t h = horizontal ? static_cast<uint32_t>(m_thickness) : 0;
    zwlr_layer_surface_v1_set_size(m_layerSurface, w, h);

    // Prevent the dock from stealing keyboard focus. Pointer events are
    // unaffected — they're controlled by the wl_surface input region, not this.
    zwlr_layer_surface_v1_set_keyboard_interactivity(
        m_layerSurface,
        ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_NONE);

    zwlr_layer_surface_v1_add_listener(m_layerSurface, &s_layerSurfaceListener, this);

    // Passing NULL to set_input_region resets to "whole surface accepts input".
    // This undoes any empty region that Qt may have set due to window flags,
    // ensuring pointer events are delivered even without keyboard focus.
    // applyInputMask() re-narrows it afterwards if the dock is auto-hidden —
    // hence dropping the cached mask, which no longer matches the surface.
    wl_surface_set_input_region(surface, nullptr);
    m_maskApplied = false;

    wl_surface_commit(surface);

    // Wait for the compositor to send us the first configure event so we
    // know our actual geometry before the first frame is rendered.
    auto *display = static_cast<wl_display *>(
        ni->nativeResourceForIntegration("wl_display"));
    if (display)
        wl_display_roundtrip(display);
}

void LayerShellWindow::applyX11Geometry()
{
    QScreen *scr = screen() ? screen() : QGuiApplication::primaryScreen();
    if (!scr) return;

    // Changing flags recreates the native window on XCB, which drops the
    // XShape input mask with it.
    setFlags(Qt::BypassWindowManagerHint | Qt::FramelessWindowHint
             | Qt::WindowStaysOnTopHint);
    m_maskApplied = false;

    const QRect geom = scr->availableGeometry();

    if (m_anchor == QStringLiteral("bottom")) {
        setGeometry(geom.x(), geom.y() + geom.height() - m_thickness,
                    geom.width(), m_thickness);
    } else if (m_anchor == QStringLiteral("top")) {
        setGeometry(geom.x(), geom.y(), geom.width(), m_thickness);
    } else if (m_anchor == QStringLiteral("left")) {
        setGeometry(geom.x(), geom.y(), m_thickness, geom.height());
    } else {
        setGeometry(geom.x() + geom.width() - m_thickness, geom.y(),
                    m_thickness, geom.height());
    }
}

void LayerShellWindow::setAnchor(const QString &anchor)
{
    m_anchor = anchor;
}

void LayerShellWindow::setLayer(const QString &layer)
{
    m_layer = layer;
}

void LayerShellWindow::setThickness(int px)
{
    m_thickness = px;
}

void LayerShellWindow::setExclusiveZone(int px)
{
    m_exclusiveZone = px;
}

void LayerShellWindow::setInteractiveThickness(int px)
{
    if (m_interactiveThickness == px) return;
    m_interactiveThickness = px;
    applyInputMask();
}

void LayerShellWindow::applyGeometryUpdate()
{
    if (!m_isWayland || !m_layerSurface) return;

    QPlatformNativeInterface *ni = QGuiApplication::platformNativeInterface();
    if (!ni) return;

    auto *surface = static_cast<wl_surface *>(
        ni->nativeResourceForWindow("wl_surface", this));
    if (!surface) return;

    zwlr_layer_surface_v1_set_exclusive_zone(m_layerSurface, m_exclusiveZone);

    // The surface is always the full configured thickness. Auto-hide is done
    // by narrowing the input region (applyInputMask), never by resizing —
    // a resize here would make the compositor churn pointer enter/leave and
    // the dock would flicker while the cursor sat on it (issue #3).
    const bool horizontal = (m_anchor == QStringLiteral("bottom")
                          || m_anchor == QStringLiteral("top"));
    const uint32_t w = horizontal ? 0 : static_cast<uint32_t>(m_thickness);
    const uint32_t h = horizontal ? static_cast<uint32_t>(m_thickness) : 0;
    zwlr_layer_surface_v1_set_size(m_layerSurface, w, h);

    wl_surface_commit(surface);

    auto *display = static_cast<wl_display *>(
        ni->nativeResourceForIntegration("wl_display"));
    if (display)
        wl_display_roundtrip(display);

    // A thickness change moves the edge the reveal strip clings to.
    applyInputMask();
}

void LayerShellWindow::resizeEvent(QResizeEvent *event)
{
    QQuickView::resizeEvent(event);
    // The mask is expressed in window coordinates, so it has to be recomputed
    // whenever the compositor hands us a new size.
    applyInputMask();
}

void LayerShellWindow::applyInputMask()
{
    if (!isVisible()) return;

    const int w = width();
    const int h = height();
    if (w <= 0 || h <= 0) return;

    const bool vertical = (m_anchor == QStringLiteral("left")
                        || m_anchor == QStringLiteral("right"));
    const int available = vertical ? w : h;

    // Hidden: only the reveal strip listens, so everything else falls through
    // to the window underneath. Revealed: the band the dock actually occupies,
    // never the whole window — the click-bounce headroom above it paints
    // nothing and must not intercept pointer events.
    const int band = m_revealed
                   ? (m_interactiveThickness > 0 ? m_interactiveThickness : available)
                   : kRevealStripPx;
    const int strip = qBound(1, band, available);

    QRegion mask;
    if (m_anchor == QStringLiteral("bottom"))
        mask = QRegion(0, h - strip, w, strip);
    else if (m_anchor == QStringLiteral("top"))
        mask = QRegion(0, 0, w, strip);
    else if (m_anchor == QStringLiteral("left"))
        mask = QRegion(0, 0, strip, h);
    else
        mask = QRegion(w - strip, 0, strip, h);

    if (m_maskApplied && m_appliedMask == mask) return;
    m_appliedMask = mask;
    m_maskApplied = true;
    setMask(mask);
}

void LayerShellWindow::setRevealed(bool revealed)
{
    if (m_revealed == revealed) return;
    m_revealed = revealed;
    applyInputMask();
}

void LayerShellWindow::reanchorToScreen(QScreen *targetScreen)
{
    if (!targetScreen || screen() == targetScreen) return;

    setScreen(targetScreen);

    if (m_isWayland && m_layerShell) {
        if (m_layerSurface) {
            zwlr_layer_surface_v1_destroy(m_layerSurface);
            m_layerSurface = nullptr;
        }
        // setupWaylandLayerSurface() re-reads screen() for the wl_output, so
        // it picks up targetScreen and rebinds the layer-shell role there.
        setupWaylandLayerSurface();
    } else {
        applyX11Geometry();
    }

    // Recreating the surface reset its input region to "everything".
    applyInputMask();
}
